#!/usr/bin/env ruby

dir = ARGV[0]

Dir.chdir(dir) do
  system "mogrify -format jpg *.HEIC"
  system "rm -f *.HEIC"
  system "mogrify -path '#{dir}' -resize 1920x1920 -quality 90 -auto-level -normalize '#{dir}/*'"
end
